apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: bb1uaq4wr-nodejs
  janus-idp.io/tekton: bb1uaq4wr-nodejs
  backstage.io/kubernetes-id: bb1uaq4wr-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: bb1uaq4wr-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
